build:
    environment:
        sdkman:
            - maven
    tests:
        override:
            -
                command: mvn clean package
                coverage:
                    file: 'src/main/java'
                    format: 'jacoco'
