build:
    environment:
        java: java-8-oracle
        sdkman:
            - maven

    filter:
        excluded_paths:
            - src/test/*

    tests:
        override:
            -
                command: mvn clean package
                coverage:
                    file: 'jacoco.xml'
                    format: 'jacoco'
