language: java

jdk:
  - oraclejdk8

script:
  - mvn install -Dgpg.skip=true -Dmaven.javadoc.skip=true

after_success:
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar https://idrinth.de/codacy-coverage-reporter-assembly-latest.jar
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
