language: java
sudo: false

jdk:
  - oraclejdk8

script: mvn clean verify

after_success:
  - mvn clean test
  - mvn org.jacoco:report
  - mvn org.eluder.coveralls.coveralls:report -DrepoToken="${COVERALLS_TOKEN}"
